// flow-typed signature: 41df610eebd16697e0b0098f9d91c5b8
// flow-typed version: <<STUB>>/event-emitter-es6_v^1.1.5/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'event-emitter-es6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'event-emitter-es6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'event-emitter-es6/dist/event-emitter' {
  declare module.exports: any;
}

declare module 'event-emitter-es6/dist/event-emitter.min' {
  declare module.exports: any;
}

declare module 'event-emitter-es6/router/index' {
  declare module.exports: any;
}

declare module 'event-emitter-es6/test/emitting_spec' {
  declare module.exports: any;
}

declare module 'event-emitter-es6/test/listeners_spec' {
  declare module.exports: any;
}

declare module 'event-emitter-es6/test/passing-arguments_spec' {
  declare module.exports: any;
}

declare module 'event-emitter-es6/test/strict-mode_spec' {
  declare module.exports: any;
}

declare module 'event-emitter-es6/test/test-helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'event-emitter-es6/dist/event-emitter.js' {
  declare module.exports: $Exports<'event-emitter-es6/dist/event-emitter'>;
}
declare module 'event-emitter-es6/dist/event-emitter.min.js' {
  declare module.exports: $Exports<'event-emitter-es6/dist/event-emitter.min'>;
}
declare module 'event-emitter-es6/index' {
  declare module.exports: $Exports<'event-emitter-es6'>;
}
declare module 'event-emitter-es6/index.js' {
  declare module.exports: $Exports<'event-emitter-es6'>;
}
declare module 'event-emitter-es6/router/index.js' {
  declare module.exports: $Exports<'event-emitter-es6/router/index'>;
}
declare module 'event-emitter-es6/test/emitting_spec.js' {
  declare module.exports: $Exports<'event-emitter-es6/test/emitting_spec'>;
}
declare module 'event-emitter-es6/test/listeners_spec.js' {
  declare module.exports: $Exports<'event-emitter-es6/test/listeners_spec'>;
}
declare module 'event-emitter-es6/test/passing-arguments_spec.js' {
  declare module.exports: $Exports<'event-emitter-es6/test/passing-arguments_spec'>;
}
declare module 'event-emitter-es6/test/strict-mode_spec.js' {
  declare module.exports: $Exports<'event-emitter-es6/test/strict-mode_spec'>;
}
declare module 'event-emitter-es6/test/test-helper.js' {
  declare module.exports: $Exports<'event-emitter-es6/test/test-helper'>;
}
