// flow-typed signature: 70ee608267c5f85de4dd160218a6c9a8
// flow-typed version: <<STUB>>/monotonic-timestamp_v^0.0.9/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'monotonic-timestamp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'monotonic-timestamp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'monotonic-timestamp/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'monotonic-timestamp/index' {
  declare module.exports: $Exports<'monotonic-timestamp'>;
}
declare module 'monotonic-timestamp/index.js' {
  declare module.exports: $Exports<'monotonic-timestamp'>;
}
declare module 'monotonic-timestamp/test/index.js' {
  declare module.exports: $Exports<'monotonic-timestamp/test/index'>;
}
